### ISSUE TITLE
any example to use addChannel

### ISSUE THREAD

**Issue by enoshima** [ghorn/Plot-ho-matic#12]
Hello,

I am very interested in your project! 
I am curious how to use addChannel. Could you show an example to user addChannel?
Thank you in advance.

Best,
Kazu

**Comment by ghorn** [comment]
Add channel is for adding things where you want to specify the X axis manually. It isn't currently well documented but it works fine.

I use it here to monitor trajectory optimization codes: 
https://github.com/ghorn/dynobud/blob/master/src/Dyno/DirectCollocation/Dynamic.hs#L55-L57

**Comment by enoshima** [comment]
Thank you very much!!
Best,
Kazu

**Comment by ghorn** [comment]
I'll leave this open as a reminder. I'm working on improving documentation

**Comment by ghorn** [comment]
Added a link to `addHistoryChannel`

**Comment by ghorn** [comment]
https://github.com/ghorn/Plot-ho-matic/commit/03d50babd252dc6202fbbb8df209e1aabf77d9d2
